nelmio_api_doc:
    documentation:
        info:
            title: File Cloud API
            description: Local file cloud with web access
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1
